{% set version = "0.4.1" %}

# conda build -c esteinig -c bioconda -c conda-forge .

package:
  name: sketchy
  version: {{ version }}

source:
  path: .

build:
  number: 0
  entry_points:
    - sketchy = sketchy.terminal.client:terminal_client

requirements:
  build:
      - {{ compiler('cxx') }}
  host:
      - python>=3.7
      - rust>=1.39
      - mash=2.2
      - wget
      - pysam
      - nextflow
      - tqdm
      - colorama
      - pandas
      - click
      - pytest
      - seaborn
      - scipy
      - python-dateutil
      - numpy
      - pysam
      - matplotlib
      - deprecation
      - braceexpand
      - pf-core
      - networkx
      - pyfastx
      - watchdog
      - psutil
      - google-cloud-storage
  run:
      - python>=3.7
      - rust>=1.39
      - mash=2.2
      - wget
      - pysam
      - nextflow
      - tqdm
      - colorama
      - pandas
      - click
      - pytest
      - seaborn
      - scipy
      - python-dateutil
      - numpy
      - pysam
      - psutil
      - matplotlib
      - deprecation
      - braceexpand
      - pf-core
      - networkx
      - pyfastx
      - watchdog
      - google-cloud-storage
test:
  commands:
    - sketchy-rs -h
    - sketchy --help

about:
  home: 'https://github.com/esteinig/sketchy'
  license: MIT
  license_file: LICENSE
  summary: 'Real-time lineage hashing and genotyping of bacterial pathogens using genomic neighbor typing'

