{% set version = "0.4.3" %}
{% set name = "sketchy" %}

# conda build -c esteinig -c bioconda -c conda-forge .
package:
  name:               {{ name }}
  version:            {{ version }}

source:
  path:               .

build:
  number:             0
  entry_points:
    - sketchy = sketchy.terminal.client:terminal_client

requirements:
  build:
      - {{ compiler('cxx') }}
      - rust >=1.39
  host:
      - python ==3.7
  run:
      - python ==3.7
      - mash ==2.2
      - wget
      - nextflow
      - tqdm
      - colorama
      - pandas
      - click
      - pytest
      - seaborn
      - scipy
      - python-dateutil
      - numpy
      - pysam
      - psutil
      - matplotlib-base
      - deprecation
      - braceexpand
      - networkx
      - pyfastx
      - watchdog
      - dendropy
test:
  imports:
    - sketchy
  commands:
    - sketchy --help
    - sketchy-rs -h

about:
  home:               https://github.com/esteinig/sketchy
  license:            MIT
  license_file:       LICENSE
  summary:            'Real-time lineage hashing and genotyping of bacterial pathogens'

extra:
  recipe-maintainers:
    - esteinig
    - mbhall88
