{% set version = "0.3.a3" %}

package:
  name: sketchy
  version: {{ version }}

source:
  url: https://github.com/esteinig/sketchy/archive/v{{ version }}.tar.gz # [linux64,linux32]

build:
  number: 0
  script: python -m pip install . -vv

requirements:
  build:
      - python=3.7
      - pip
  host:
      - python=3.7
      - pip
  run:
      - python=3.7
      - tqdm
      - colorama
      - pandas
      - click
      - pytest
      - seaborn
      - scipy
      - biopython
      - pypdf2
      - pysam
      - mash

test:
  commands:
      - sketchy --help
      - mash dist -h

about:
  home: 'https://github.com/esteinig/sketchy'
  license: MIT
  license_file: LICENSE
  summary: 'Real-time lineage hashing and genotyping of bacterial pathogens from uncorrected nanopore reads.'

